package com.eventbooking.mapper;

import com.eventbooking.dto.response.EventResponse;
import com.eventbooking.entity.Event;
import org.springframework.stereotype.Component;

/**
 * Maps between Event entity and EventResponse DTO.
 * Centralises mapping logic that was previously duplicated inside EventService.
 */
@Component
public class EventMapper {

    public EventResponse toResponse(Event e) {
        if (e == null) return null;
        return EventResponse.builder()
                .id(e.getId())
                .eventName(e.getEventName())
                .description(e.getDescription())
                .category(e.getCategory())
                .eventType(e.getEventType())
                .collegeName(e.getCollegeName())
                .departmentName(e.getDepartmentName())
                .eventBanner(e.getEventBanner())
                .eventDate(e.getEventDate())
                .eventTime(e.getEventTime())
                .endDate(e.getEndDate())
                .endTime(e.getEndTime())
                .registrationDeadline(e.getRegistrationDeadline())
                .venueName(e.getVenueName())
                .location(e.getLocation())
                .googleMapsUrl(e.getGoogleMapsUrl())
                .whatsappGroupLink(e.getWhatsappGroupLink())
                .whatsappContactNumber(e.getWhatsappContactNumber())
                .venueLatitude(e.getVenueLatitude())
                .venueLongitude(e.getVenueLongitude())
                .ticketPrice(e.getTicketPrice())
                .totalSeats(e.getTotalSeats())
                .availableSeats(e.getAvailableSeats())
                .status(e.getStatus())
                .visibility(e.getVisibility())
                .featured(e.isFeatured())
                .hasCertificate(e.isHasCertificate())
                .certificateSettings(e.getCertificateSettings() != null
                        ? EventResponse.CertificateSettingsInfo.builder()
                                .certificateAvailable(e.getCertificateSettings().isCertificateAvailable())
                                .automaticGeneration(e.getCertificateSettings().isAutomaticGeneration())
                                .releaseMode(e.getCertificateSettings().getReleaseMode())
                                .releaseDate(e.getCertificateSettings().getReleaseDate())
                                .minimumAttendanceRequired(e.getCertificateSettings().isMinimumAttendanceRequired())
                                .certificateType(e.getCertificateSettings().getCertificateType())
                                .organizerName(e.getCertificateSettings().getOrganizerName())
                                .organizationName(e.getCertificateSettings().getOrganizationName())
                                .verificationBaseUrl(e.getCertificateSettings().getVerificationBaseUrl())
                                .certificateExpiry(e.getCertificateSettings().getCertificateExpiry())
                                .theme(e.getCertificateSettings().getTheme())
                                .released(e.getCertificateSettings().isReleased())
                                .releasedAt(e.getCertificateSettings().getReleasedAt())
                                .build()
                        : null)
                .tags(e.getTags())
                .organizerDetails(e.getOrganizerDetails())
                .authorizedDocumentUrl(e.getAuthorizedDocumentUrl())
                .createdAt(e.getCreatedAt())
                .certificateDeadline(e.getCertificateDeadline())
                .completedAt(e.getCompletedAt())
                .expiredAt(e.getExpiredAt())
                .foodProvided(Boolean.TRUE.equals(e.getFoodProvided()))
                .foodMeals(e.getFoodMeals())
                .foodType(e.getFoodType())
                .teaCoffeeProvided(Boolean.TRUE.equals(e.getTeaCoffeeProvided()))
                .specialDiet(e.getSpecialDiet())
                .accommodationProvided(Boolean.TRUE.equals(e.getAccommodationProvided()))
                .accommodationType(e.getAccommodationType())
                .accommodationCharges(e.getAccommodationCharges())
                .accommodationBedsAvailable(e.getAccommodationBedsAvailable())
                .accommodationDetails(e.getAccommodationDetails())
                .boysHostelAvailable(Boolean.TRUE.equals(e.getBoysHostelAvailable()))
                .girlsHostelAvailable(Boolean.TRUE.equals(e.getGirlsHostelAvailable()))
                .hotelTieupAvailable(Boolean.TRUE.equals(e.getHotelTieupAvailable()))
                .accommodationCheckIn(e.getAccommodationCheckIn())
                .accommodationCheckOut(e.getAccommodationCheckOut())
                .accommodationContactPerson(e.getAccommodationContactPerson())
                .nearestBusStop(e.getNearestBusStop())
                .distanceFromBusStop(e.getDistanceFromBusStop())
                .busNumbers(e.getBusNumbers())
                .nearestRailwayStation(e.getNearestRailwayStation())
                .distanceFromRailwayStation(e.getDistanceFromRailwayStation())
                .nearestAirport(e.getNearestAirport())
                .metroInformation(e.getMetroInformation())
                .landmarks(e.getLandmarks())
                .parkingAvailable(e.getParkingAvailable())
                .travelGuide(e.getTravelGuide())
                .estimatedTravelTime(e.getEstimatedTravelTime())
                .cabEstimate(e.getCabEstimate())
                .nearbyHotels(e.getNearbyHotels())
                .nearbyRestaurants(e.getNearbyRestaurants())
                .emergencyContacts(e.getEmergencyContacts())
                .sessionSchedule(e.getSessionSchedule())
                .speakerList(e.getSpeakerList())
                .liveAnnouncements(e.getLiveAnnouncements())
                .reportingTime(e.getReportingTime())
                .dressCode(e.getDressCode())
                .itemsToBring(e.getItemsToBring())
                .laptopRequired(Boolean.TRUE.equals(e.getLaptopRequired()))
                .idCardRequired(Boolean.TRUE.equals(e.getIdCardRequired()))
                .teamSize(e.getTeamSize())
                .rules(e.getRules())
                .refundPolicy(e.getRefundPolicy())
                .cancellationPolicy(e.getCancellationPolicy())
                .certificateEligibility(e.getCertificateEligibility())
                .wifiAvailable(Boolean.TRUE.equals(e.getWifiAvailable()))
                .wheelchairAccessible(Boolean.TRUE.equals(e.getWheelchairAccessible()))
                .restRoomsAvailable(Boolean.TRUE.equals(e.getRestRoomsAvailable()))
                .drinkingWaterAvailable(Boolean.TRUE.equals(e.getDrinkingWaterAvailable()))
                .medicalSupportAvailable(Boolean.TRUE.equals(e.getMedicalSupportAvailable()))
                .networkingEnabled(Boolean.TRUE.equals(e.getNetworkingEnabled()))
                .organizer(e.getOrganizer() != null
                        ? EventResponse.OrganizerInfo.builder()
                                .id(e.getOrganizer().getId())
                                .organizerName(e.getOrganizer().getOrganizerName())
                                .organizationName(e.getOrganizer().getOrganizationName())
                                .organizationLogo(e.getOrganizer().getOrganizationLogo())
                                .email(e.getOrganizer().getEmail())
                                .phone(e.getOrganizer().getPhone())
                                .organizerCode(e.getOrganizer().getOrganizerCode())
                                .build()
                        : null)
                .build();
    }
}
