$ErrorActionPreference = 'Stop'
function EventObj { param($i,$title,$label,$category,$mode,$college,$dept,$city,$state,$date,$status,$price,$capacity)
  $i=[int](@($i)[0]); $price=[int](@($price)[0]); $capacity=[int](@($capacity)[0])
  $n=$i+1; $phone='91987066'+$n.ToString('0000'); $pin='600'+$n.ToString('000');
  $booked=[Math]::Min($capacity-5,[int]($capacity*(0.25+(($i%6)*0.08)))); if($status -eq 'COMPLETED'){$booked=[int]($capacity*0.82)}; if($status -eq 'CANCELLED'){$booked=0}
  $d=[datetime]$date; $regStart=$d.AddDays(-30).ToString('yyyy-MM-dd'); $regEnd=$d.AddDays(-2).ToString('yyyy-MM-dd'); if($date -eq '2026-07-12'){$regEnd='2026-07-12'}
  $venue=@('Main Auditorium','Innovation Lab','Seminar Hall A','Virtual Arena','Convention Centre','Incubation Centre','Project Gallery','Cyber Lab','Robotics Arena','Cloud Lab')[$i%10]
  $block=[char](65+($i%5)); $hall=100+$n; $rating=[Math]::Round(4.1+(($i%10)*0.09),1)
  $acc=@('HOSTEL','HOTEL','BOTH','NONE')[$i%4]; $accProv=$acc -ne 'NONE'; $accCost=if($accProv){500+(($i%5)*250)}else{0}
  $display=if($status -eq 'EXPIRED'){'Registration Closed'}else{$status.Replace('_',' ')}
  [ordered]@{
    eventName=$title; shortDescription="$label focused campus event in $city."; description="$label covering practical sessions, mentoring, networking, judging, certificates, help desk support and post-event resources. Full Description: $title brings together students, faculty and industry mentors for realistic hands-on learning and competition outcomes."; category=$category; tags=@('COMPREHENSIVE_MOCK_2026',$label,$category); eventType=$mode
    organizer=@{organizerName=@('Arjun Nair','Priya Menon','Sanjay Rao','Kavya Iyer','Rohit Sharma','Nisha Varghese','Vikram Desai','Ananya Reddy')[$i%8]; organizationName="$college $dept"; organizerEmail=('event{0:00}@eventgpt-campus.example.com' -f $n); organizerPhone=$phone; whatsAppNumber=$phone; whatsAppGroupLink=('https://chat.whatsapp.com/eventgpt2026seed{0:00}' -f $n)}
    schedule=@{registrationStartDate=$regStart; registrationEndDate=$regEnd; eventDate=$date; startTime='09:00:00'; endTime='17:30:00'}
    venue=@{venueName=$venue; collegeName=$college; building="Building Block $block"; hall="Hall $hall"; city=$city; state=$state; country='India'; pinCode=$pin}
    capacity=@{totalSeats=$capacity; bookedCount=$booked; availableSeats=($capacity-$booked)}; pricing=@{amount=$price; currency='INR'; label=if($price -eq 0){'Free'}else{'Rs '+$price}}
    eventBanner=('https://picsum.photos/seed/eventgpt2026-{0}/1200/800' -f $n); authorizedDocumentUrl=('https://example.com/documents/eventgpt2026-{0}-approval.pdf' -f $n)
    contact=@{contactPerson=@('Neha Kapoor','Aditya Kumar','Sneha Thomas','Rahul Jain','Farah Khan','Manoj Pillai','Diya Shah','Kiran Bhat')[$i%8]; mobileNumber=$phone; email=('contact{0}@eventgpt-campus.example.com' -f $n)}
    foodDetails=@{breakfastIncluded=($i%4 -in 0,2); lunchIncluded=($i%4 -ne 3); snacksIncluded=$true; dinnerIncluded=($i%4 -eq 0); vegAvailable=$true; nonVegAvailable=($i%4 -in 1,3); waterAvailable=$true}
    accommodationDetails=@{type=if($accProv){$acc}else{'No Accommodation'}; hostelAvailable=($acc -in @('HOSTEL','BOTH')); hotelPartnership=($acc -in @('HOTEL','BOTH')); guestHouse=($i%7 -eq 0); cost=$accCost; distanceFromVenue=((0.5+(($i%6)*0.4)).ToString('0.0')+' km'); bookingInstructions=if($accProv){"Email accommodation$n@eventgpt-campus.example.com with ticket ID before $regEnd."}else{'Book nearby hotels directly; organizer help desk can share suggestions.'}}
    travelAssistance=@{nearestBusStand="$city Central Bus Stand ($((1+$i%6)) km)"; busNumbers=@('5A','7C','S12'); walkingDirections="Exit bus stand, take the college route bus or cab, enter Main Gate, walk 200-600 meters to $venue."; nearestRailwayStation="$city Junction"; trainSuggestions="Use intercity or suburban services to $city Junction, then take auto or app cab."; nearestMetro=if($city -in @('Chennai','Bengaluru','Hyderabad','Mumbai','New Delhi')){'Available on city metro corridor'}else{'Not Available'}; airport="$city International Airport"; cabAvailability='Ola, Uber and local autos available'; parkingAvailability=@('Available for Cars and Bikes','Limited campus parking','Paid parking near main gate')[$i%3]}
    aiTravelGuide="If you arrive at $city Central Bus Stand, board one of the listed college-route buses towards $college. Get down at the main gate, follow signs to $venue, and report by 08:30. Railway passengers can take an auto from $city Junction. Airport passengers should use prepaid cab counters or app cabs. Parking is available as mentioned in the event details."
    socialLinks=@{website=('https://events{0}.example.edu' -f $n); instagram=('https://instagram.com/eventgpt{0}' -f $n); linkedIn=('https://linkedin.com/company/eventgpt{0}' -f $n); x=('https://x.com/eventgpt{0}' -f $n); facebook=('https://facebook.com/eventgpt{0}' -f $n)}
    certificates=@{types=@('Participation','Winner','Runner-up','Volunteer'); templateStatus='Uploaded'}; refundPolicy=if($price -eq 0){'Free event; no payment refund applies. Inform organizer before registration closes to release seat.'}else{'90% refund until 7 days before event, 50% refund until 48 hours before event, no refund after check-in or event start.'}; cancellationPolicy='Organizer may cancel or reschedule due to safety issues, speaker unavailability, low registrations or force majeure. Paid participants receive refund or transfer options within 7 working days.'
    eligibility=@('Any College Student','Engineering Students','Final Year Only','Open to Everyone')[$i%4]; prizes=@('Rs 10000','Rs 50000','Rs 100000','Goodies','Internship Opportunities','Certificates')[$i%6]; sponsors=@('TCS iON','Zoho','Freshworks')
    agenda=@('09:00 Registration','10:00 Inauguration','11:00 Keynote','12:30 Lunch','14:00 Technical Session','16:00 Awards','17:00 Closing'); faqs=@('Is college ID required? Yes.','Can other college students attend? Check eligibility.','Will certificates be provided? Yes, template uploaded.','Is food included? See food details.','Can I get a refund? See refund policy.')
    ratings=@{rating=$rating; reviewCount=(35+$i*7); registrationCount=$booked; bookmarkCount=(12+$i*5); shareCount=(20+$i*6)}; status=$status; displayStatus=$display
    apiPayload=@{eventName=$title; description="$label covering practical sessions, mentoring, networking, judging, certificates, help desk support and post-event resources."; category=$category; eventType=$mode; collegeName=$college; departmentName=$dept; eventDate=$date; eventTime='09:00:00'; endDate=$date; endTime='17:30:00'; registrationDeadline=$regEnd; venueName=$venue; location="$college, Building Block $block, Hall $hall, $city, $state, India - $pin"; whatsappGroupLink=('https://chat.whatsapp.com/eventgpt2026seed{0:00}' -f $n); whatsappContactNumber=$phone; ticketPrice=$price; totalSeats=$capacity; tags="COMPREHENSIVE_MOCK_2026,$label,$category"; authorizedDocumentUrl=('https://example.com/documents/eventgpt2026-{0}-approval.pdf' -f $n); foodProvided=$true; foodMeals='BREAKFAST,LUNCH,SNACKS'; foodType='BOTH'; teaCoffeeProvided=$true; accommodationProvided=$accProv; accommodationType=$acc; accommodationCharges=$accCost; accommodationBedsAvailable=if($accProv){30+(($i%6)*10)}else{0}; accommodationDetails="Accommodation: $acc; Cost: Rs $accCost; Distance from venue: $((0.5+(($i%6)*0.4)).ToString('0.0')) km."; nearestBusStop="$city Central Bus Stand"; distanceFromBusStop="$((1+$i%6)) km"; busNumbers='5A, 7C, S12'; nearestRailwayStation="$city Junction"; distanceFromRailwayStation="$((3+$i%8)) km"; nearestAirport="$city International Airport"; metroInformation=if($city -in @('Chennai','Bengaluru','Hyderabad','Mumbai','New Delhi')){'Available on city metro corridor'}else{'Not Available'}; parkingAvailable='FREE'; travelGuide="If you arrive at $city Central Bus Stand, board the listed buses towards $college and walk to $venue."; sessionSchedule='09:00 Registration | 10:00 Inauguration | 11:00 Keynote | 12:30 Lunch | 14:00 Technical Session | 16:00 Awards'; organizerDetails="Organizer Email: event$n@eventgpt-campus.example.com; Contact: $phone; Website: https://events$n.example.edu; Sponsors listed in source object."; status=$status; visibility='PUBLIC'; hasCertificate=$true; refundPolicy='See source object refundPolicy'; cancellationPolicy='See source object cancellationPolicy'; certificateEligibility='Minimum 75% attendance and valid registration required.'}
  }
}
$titles=@('CodeYatra National Hackathon','React Native App Workshop','Pragati Tech Symposium','AlgoArena Coding Contest','Bharat AI Research Conference','BlockEdge Blockchain Summit','SmartThings IoT Expo','Cyber Kavach Security Bootcamp','RoboNexus Challenge','CloudOps Kubernetes Lab','DataVerse Science Summit','ML Model Sprint','DevOps Pipeline Day','Campus Startup Pitch League','DesignSutra UI UX Jam','Career Connect Engineering Fair','FinTech AI Hack Day','Rhythm Raaga Cultural Fest','Inter College Sports Meet','LensCraft Photography Walk','Founder Forge Entrepreneurship Summit','GitOps and SRE Workshop','Women in Cyber Security Forum','Deep Learning Masterclass','GreenTech Innovation Hackathon','Quantum Computing Colloquium','Product Management Pitch Night','No Code Automation Workshop','Drone Robotics Expo','GenAI Prompt Engineering Lab','Sustainable Blockchain Forum','Open Source Contribution Day')
$labels=@('Hackathon','Workshop','Technical Symposium','Coding Contest','AI Conference','Blockchain Summit','IoT Expo','Cyber Security','Robotics','Cloud Computing','Data Science','Machine Learning','DevOps','Startup Pitch','UI/UX','Career Fair','Hackathon','Cultural Fest','Sports Meet','Photography','Entrepreneurship','DevOps','Cyber Security','Machine Learning','Hackathon','Cloud Computing','Startup Pitch','Workshop','Robotics','AI Conference','Blockchain Summit','Coding Contest')
$cats=@('HACKATHON','WORKSHOP','TECHNICAL_SYMPOSIUM','CODING_COMPETITION','SEMINAR','TECHNICAL_SYMPOSIUM','PROJECT_EXHIBITION','SEMINAR','TECHNICAL_SYMPOSIUM','WORKSHOP','TECHNICAL_TRAINING','TECHNICAL_TRAINING','TECHNICAL_SYMPOSIUM','CLUB_ACTIVITY','WORKSHOP','TECHNICAL_TRAINING','HACKATHON','CULTURAL','SPORTS','CLUB_ACTIVITY','WORKSHOP','TECHNICAL_TRAINING','SEMINAR','TECHNICAL_TRAINING','HACKATHON','TECHNICAL_SYMPOSIUM','CLUB_ACTIVITY','WORKSHOP','PROJECT_EXHIBITION','SEMINAR','TECHNICAL_SYMPOSIUM','INTER_COLLEGE')
$modes=@('OFFLINE','HYBRID','OFFLINE','ONLINE','HYBRID','OFFLINE','OFFLINE','HYBRID','OFFLINE','ONLINE','HYBRID','ONLINE','OFFLINE','OFFLINE','HYBRID','OFFLINE','HYBRID','OFFLINE','OFFLINE','OFFLINE','HYBRID','ONLINE','HYBRID','ONLINE','OFFLINE','HYBRID','OFFLINE','ONLINE','OFFLINE','ONLINE','HYBRID','OFFLINE')
$colleges=@('IIT Madras','Anna University','PSG College of Technology','VIT Vellore','SRM Institute of Science and Technology','Amrita Vishwa Vidyapeetham','Kongu Engineering College','Coimbatore Institute of Technology','NIT Tiruchirappalli','SASTRA Deemed University','Kumaraguru College of Technology','Rajalakshmi Engineering College','SSN College of Engineering','Thiagarajar College of Engineering','BMS College of Engineering','PES University','RV College of Engineering','Christ University','St. Josephs College of Engineering','Hindustan Institute of Technology and Science','Manipal Institute of Technology','IIT Hyderabad','Osmania University','JNTU Hyderabad','IIT Bombay','VJTI Mumbai','COEP Technological University','MIT World Peace University','IIT Delhi','DTU Delhi','Chandigarh University','Lovely Professional University')
$cities=@('Chennai','Chennai','Coimbatore','Vellore','Chennai','Coimbatore','Erode','Coimbatore','Tiruchirappalli','Thanjavur','Coimbatore','Chennai','Chennai','Madurai','Bengaluru','Bengaluru','Bengaluru','Bengaluru','Chennai','Chennai','Manipal','Hyderabad','Hyderabad','Hyderabad','Mumbai','Mumbai','Pune','Pune','New Delhi','New Delhi','Chandigarh','Jalandhar')
$states=@('Tamil Nadu','Tamil Nadu','Tamil Nadu','Tamil Nadu','Tamil Nadu','Tamil Nadu','Tamil Nadu','Tamil Nadu','Tamil Nadu','Tamil Nadu','Tamil Nadu','Tamil Nadu','Tamil Nadu','Tamil Nadu','Karnataka','Karnataka','Karnataka','Karnataka','Tamil Nadu','Tamil Nadu','Karnataka','Telangana','Telangana','Telangana','Maharashtra','Maharashtra','Maharashtra','Maharashtra','Delhi','Delhi','Punjab','Punjab')
$dept=@('Computer Science','Information Technology','All Engineering Departments','Computer Science','Artificial Intelligence','Computer Science','Electronics and Communication','Cyber Security','Mechanical Engineering','Cloud Computing','Data Science','Artificial Intelligence','Information Technology','Entrepreneurship Cell','Design Club','Training and Placement','Computer Science','Cultural Committee','Physical Education','Photography Club','Entrepreneurship Cell','Computer Science','Cyber Security Cell','Data Science','Innovation Cell','Physics and Computer Science','Management Cell','Information Technology','Aeronautical Engineering','AI Club','Computer Science','Open Source Club')
$dates=@('2026-05-10','2026-06-18','2026-07-05','2026-07-09','2026-07-12','2026-07-12','2026-07-20','2026-07-24','2026-07-28','2026-07-30','2026-04-22','2026-06-30','2026-08-03','2026-08-08','2026-08-12','2026-08-16','2026-07-12','2026-03-15','2026-09-02','2026-07-18','2026-09-08','2026-09-12','2026-02-20','2026-06-25','2026-09-18','2026-07-12','2026-10-04','2026-10-09','2026-01-30','2026-10-18','2026-11-02','2026-11-15')
$statuses=@('COMPLETED','COMPLETED','EXPIRED','CANCELLED','LIVE','APPROVED','PENDING_APPROVAL','DRAFT','APPROVED','LIVE','COMPLETED','EXPIRED','APPROVED','PENDING_APPROVAL','DRAFT','APPROVED','LIVE','COMPLETED','APPROVED','CANCELLED','APPROVED','PENDING_APPROVAL','COMPLETED','EXPIRED','APPROVED','LIVE','DRAFT','APPROVED','COMPLETED','APPROVED','PENDING_APPROVAL','APPROVED')
$prices=@(199,99,299,99,499,299,0,199,299,199,299,499,299,0,99,0,999,0,0,99,299,199,0,499,299,499,199,99,299,199,499,0)
$caps=@(250,100,500,150,500,250,150,100,100,150,250,100,150,100,100,500,250,500,500,50,250,100,250,150,250,500,100,150,150,250,250,500)
$events=@(); for($i=0;$i -lt 32;$i++){ $events += EventObj $i ($titles[$i]) ($labels[$i]) ($cats[$i]) ($modes[$i]) ($colleges[$i]) ($dept[$i]) ($cities[$i]) ($states[$i]) ($dates[$i]) ($statuses[$i]) ($prices[$i]) ($caps[$i]) }
[ordered]@{note='Generated comprehensive mock data for Event Booking System. Use apiPayload for direct Event Creation API calls; source fields include requested full details.'; generatedAt='2026-07-12'; eventCount=$events.Count; events=$events} | ConvertTo-Json -Depth 20 | Set-Content -Path 'backend\sql\comprehensive-mock-events-2026.json' -Encoding UTF8





